import argparse
import os
import re
import sys
from pathlib import Path
import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import scipy
import torch
import torch.nn as nn

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from RNN_Class import ElmanRNN, ElmanRNN_tp1
from helper import Grid_PF, MI_Grid


BIGGER_SIZE = 14


def parse_args():
    parser = argparse.ArgumentParser(description="Reproduce Fig.5 panels")
    parser.add_argument(
        "--data-file",
        default="data/InputNs50_SeqN100_StraightTraj_Marcus_v2.pth.tar",
        type=str,
        help="Input dataset generated by Localization_clean.py",
    )
    parser.add_argument(
        "--model-dir",
        default="Elman_SGD/GridInput/BatchTraining",
        type=str,
        help="Directory containing trained checkpoints",
    )
    parser.add_argument(
        "--model-prefix",
        default="PhysicalInput_v2/repeats/InputNs50_SeqN100_Marcus_HN500_H5.0",
        type=str,
        help="Checkpoint prefix before _repK / _tp1_repK",
    )
    parser.add_argument(
        "--traj-file",
        default="Localization/StraightTraj_v2.txt",
        type=str,
        help="Trajectory txt file",
    )
    parser.add_argument(
        "--input-mi-file",
        default="PhysicalInput_v2/InputNs50_SeqN100_Marcus_HN500_H5.0_tp1_input_MI_second.pth.tar",
        type=str,
        help="Path under model-dir for input MI file used in boxplot",
    )
    parser.add_argument(
        "--tag",
        default=1,
        type=int,
        choices=[0, 1],
        help="1: predictive model, 0: non-predictive model",
    )
    parser.add_argument(
        "--hidden-n", default=500, type=int, help="Hidden size used during training"
    )
    parser.add_argument(
        "--repeats", default=10, type=int, help="Number of repeated runs to aggregate"
    )
    parser.add_argument(
        "--device", default="cpu", type=str, help="cpu or cuda:0"
    )
    return parser.parse_args()


def load_traj(path, ns, seqn):
    traj = np.loadtxt(path, delimiter="\t", unpack=False)
    return traj[3:5, : seqn * ns]


def build_model(tag, n, hidden_n, device):
    if tag:
        model = ElmanRNN_tp1(n, hidden_n, n)
    else:
        model = ElmanRNN(n, hidden_n, n)
    model.act = nn.Sigmoid()
    model.tanh = nn.ReLU()
    model = model.to(device)
    model.eval()
    return model


def run_hidden_activity(model, x_mini, hidden_n, device):
    x_device = x_mini.to(device)
    ns, seqn, n = x_mini.shape
    ht_seq = np.zeros((ns, seqn, hidden_n))
    htp1_seq = np.zeros((ns, seqn, hidden_n))
    output = np.zeros((ns, seqn, n))
    ht = torch.zeros((1, ns, hidden_n), device=device)
    with torch.no_grad():
        for t in range(seqn):
            o, ht = model(x_device[:, t : t + 1, :], ht)
            htp1 = model.tanh(model.hidden_linear(ht))
            output[:, t : t + 1, :] = o.detach().cpu().numpy()
            ht_seq[:, t, :] = ht[0, :, :].detach().cpu().numpy()
            htp1_seq[:, t, :] = htp1[0, :, :].detach().cpu().numpy()
    return output, ht_seq, htp1_seq


def compute_mi_pool(tag, ht_seq, htp1_seq, loc, hidden_n):
    pf_pool = []
    neuron_list = []
    i_list = []
    for neuron in range(hidden_n):
        if tag:
            activity = np.abs(htp1_seq[:, :, neuron].reshape(-1, 1))
        else:
            activity = np.abs(ht_seq[:, :, neuron].reshape(-1, 1))
        pf = Grid_PF(activity, loc, 20)
        if np.nanmean(pf) < 0.01:
            continue
        info = MI_Grid(activity, loc, 20)
        i_list.append(info)
        neuron_list.append(neuron)
        pf_pool.append(pf)
    return i_list, neuron_list, pf_pool


def ensure_exists(path):
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing required file: {path}")


def main():
    args = parse_args()
    device = torch.device(args.device)

    ensure_exists(args.data_file)
    ensure_exists(args.traj_file)

    data = torch.load(args.data_file, map_location="cpu")
    x_mini = data["X_mini"]
    ns, seqn, n = x_mini.shape
    loc = load_traj(args.traj_file, ns, seqn)

    # Panel B: use rep1
    model_name = f"{args.model_prefix}{'_tp1' if args.tag else ''}_rep1"
    ckpt_path = os.path.join(args.model_dir, model_name + ".pth.tar")
    ensure_exists(ckpt_path)
    net = torch.load(ckpt_path, map_location=device)
    model = build_model(args.tag, n, args.hidden_n, device)
    model.load_state_dict(net["state_dict"])
    output, ht_seq, htp1_seq = run_hidden_activity(model, x_mini, args.hidden_n, device)

    print(np.mean((output - x_mini.numpy()) ** 2))  # loss per batch
    print(np.mean((x_mini.numpy()) ** 2))  # baseline value per batch
    print(net["loss"][-1])  # training loss

    i_list, neuron_list, pf_pool = compute_mi_pool(
        args.tag, ht_seq, htp1_seq, loc, args.hidden_n
    )

    idx = np.argsort(i_list)[::-1]
    plt.figure(figsize=(12, 12))
    plt.rc("font", size=BIGGER_SIZE)
    for c, i in enumerate(idx[:42]):
        plt.subplot(6, 7, c + 1)
        plt.imshow(pf_pool[i].T)
        plt.title("MI={:.2f}".format(i_list[i]))
        plt.gca().invert_yaxis()
        plt.axis("off")

    os.makedirs(os.path.dirname(ckpt_path), exist_ok=True)
    panel_b_out = os.path.join(args.model_dir, model_name + "_PF_ht_MI_second_selected.pdf")
    plt.tight_layout()
    plt.savefig(panel_b_out)
    plt.close()

    torch.save(
        {"I_list": i_list, "neuron_list": neuron_list},
        os.path.join(args.model_dir, model_name + "_ht_MI_second.pth.tar"),
    )

    # Panel C: MI distribution over repeated training
    loss_true_rep = []
    loss_rep = []
    i_rep = []
    loaded_names = []
    for trial in range(1, args.repeats + 1):
        rep_name = f"{args.model_prefix}{'_tp1' if args.tag else ''}_rep{trial}"
        rep_path = os.path.join(args.model_dir, rep_name + ".pth.tar")
        if not os.path.exists(rep_path):
            print(f"[skip] missing checkpoint: {rep_path}")
            continue
        loaded_names.append(rep_name)

        net = torch.load(rep_path, map_location=device)
        model = build_model(args.tag, n, args.hidden_n, device)
        model.load_state_dict(net["state_dict"])
        output, ht_seq, htp1_seq = run_hidden_activity(model, x_mini, args.hidden_n, device)
        print(np.mean((output - x_mini.numpy()) ** 2))
        print(np.mean((x_mini.numpy()) ** 2))
        print(net["loss"][-1])

        i_trial, _, _ = compute_mi_pool(args.tag, ht_seq, htp1_seq, loc, args.hidden_n)
        i_rep.append(i_trial)
        loss_rep.append(net["loss"][-1])
        loss_true_rep.append(np.mean((output - x_mini.numpy()) ** 2))

    if not loaded_names:
        raise RuntimeError("No repeated checkpoints found; cannot compute Panel C.")

    if args.tag:
        valid_idx = np.where(np.array(loss_rep) < 0.02)[0]
    else:
        valid_idx = np.arange(len(loss_rep))

    i_list_all = []
    loss_list = []
    loss_true_list = []
    for i in valid_idx:
        i_list_all.extend(i_rep[i])
        loss_list.append(loss_rep[i])
        loss_true_list.append(loss_true_rep[i])

    last_name = loaded_names[-1]
    rep_prefix = re.sub(r"\d+$", "", last_name)
    if args.tag:
        save_name = os.path.join(args.model_dir, rep_prefix + "_htp1_MI_second.pth.tar")
    else:
        save_name = os.path.join(args.model_dir, rep_prefix + "_ht_MI_second.pth.tar")

    torch.save(
        {"I_list": i_list_all, "loss_list": loss_list, "loss_true_list": loss_true_list},
        save_name,
    )
    print(f"Saved MI summary: {save_name}")

    # Optional boxplot if all summary files are available
    current_path = os.path.join(args.model_dir, args.model_prefix + "_rep_ht_MI_second.pth.tar")
    pred_path = os.path.join(args.model_dir, args.model_prefix + "_tp1_rep_htp1_MI_second.pth.tar")
    input_path = os.path.join(args.model_dir, args.input_mi_file)
    if not (os.path.exists(current_path) and os.path.exists(pred_path) and os.path.exists(input_path)):
        print("Skip final boxplot: one or more MI summary files are missing.")
        print(f"Expected: {current_path}")
        print(f"Expected: {pred_path}")
        print(f"Expected: {input_path}")
        return

    current = torch.load(current_path, map_location="cpu")
    pred = torch.load(pred_path, map_location="cpu")
    input_data = torch.load(input_path, map_location="cpu")

    print(np.mean(current["I_list"]))
    print(np.mean(pred["I_list"]))
    print(np.mean(input_data["I_list"]))
    _, p = scipy.stats.ttest_ind(current["I_list"], pred["I_list"])

    plt.figure(figsize=(3, 3.5))
    bplot = plt.boxplot(
        [input_data["I_list"], current["I_list"], pred["I_list"]],
        showfliers=False,
        patch_artist=True,
        notch=True,
        labels=["Input", "Current", "Predictive"],
    )
    for patch, color in zip(bplot["boxes"], ["tab:green", "tab:blue", "tab:orange"]):
        patch.set_facecolor(color)

    plt.rc("font", size=BIGGER_SIZE)
    plt.ylabel("MI")
    ylims = plt.ylim()
    plt.ylim([ylims[0], ylims[1] * 1.1])
    plt.xticks(rotation=45, ha="right")
    plt.title("Pvalue={:.2e}".format(p))
    plt.tight_layout()
    plt.savefig(os.path.join(args.model_dir, args.model_prefix + "_ReLU_H2.0_MI_second_boxplot2.pdf"))
    plt.close()


if __name__ == "__main__":
    main()
